version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      VitePress:
        patterns:
          - vitepress
      TypeScript:
        patterns:
          - typescript
          - "@types/*"
      ESLint:
        patterns:
          - eslint
          - "@typescript-eslint/*"
      Lint:
        patterns:
          - prettier
          - markdownlint
