version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: "/"
    reviewers:
      - 'krudi'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'build(deps)'

  - package-ecosystem: 'npm'
    directory: '/'
    reviewers:
      - 'krudi'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'build(deps)'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
    groups:
      framework:
        patterns:
          - 'vitepress'
        update-types:
          - 'minor'

      linting-and-formatting:
        patterns:
          - 'eslint'
          - 'eslint-config-prettier'
          - 'eslint-plugin-simple-import-sort'
          - '@eslint/js'
          - 'prettier'
          - 'markdownlint'
          - 'markdownlint-cli'
        update-types:
          - 'minor'

      typings:
        patterns:
          - '@types/node'
        update-types:
          - 'minor'

      build-tools:
        patterns:
          - 'typescript'
          - 'ts-node'
          - 'typescript-eslint'
        update-types:
          - 'minor'
