printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: false
trailingComma: none
bracketSpacing: true
arrowParens: always
bracketSameLine: false
singleAttributePerLine: false
rangeStart: 0
rangeEnd: 1
requirePragma: true
insertPragma: true
proseWrap: always
