name: Set up and build project

on:
    push:
        branches:
            - develop
            - main
            - '!dependabot/**'

    pull_request:
        branches:
            - develop
            - main
            - '!dependabot/**'

jobs:
    build:
        name: Install dependencies and build project
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version:
                    - '22.14.0'

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: '${{ matrix.node-version }}'
                  cache: npm

            - name: Install Node.js dependencies
              run: npm install

            - name: Compile and build project
              run: npm run build
