name: Frontend linting and code quality checks

on:
    push:
        paths:
            - '**/*.md'

        branches:
            - develop
            - main
            - '!dependabot/**'

    pull_request:
        paths:
            - '**/*.md'

        branches:
            - develop
            - main
            - '!dependabot/**'

jobs:
    build:
        name: Install dependencies and build project
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version:
                    - '22.14.0'
                command:
                    - 'lint:markdown'

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: '${{ matrix.node-version }}'
                  cache: npm

            - name: Install Node.js dependencies
              run: npm install

            - name: Run linting command(s)
              run: 'npm run ${{ matrix.command }}'
